---
version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - TZ=${TZ} # Specify a timezone to use
      - PUID=${PUID} # User ID to run as
      - PGID=${PGID} # Group ID to run as
      - WEBUI_PORT=8080
    volumes:
      - ${CONFIGDIR}/qbittorrent:/config
      - ${PLEXDATA}:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped