---
version: "2.1"
services:
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - TZ=${TZ} # Specify a timezone to use
      - PUID=${PUID} # User ID to run as
      - PGID=${PGID} # Group ID to run as
    volumes:
      - ${CONFIGDIR}/overseerr:/config
    ports:
      - 5055:5055
    restart: unless-stopped