---
version: "2.1"
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - TZ=${TZ} # Specify a timezone to use
      - PUID=${PUID} # User ID to run as
      - PGID=${PGID} # Group ID to run as
    volumes:
      - ${CONFIGDIR}/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped