version: "3.7"

services:
  heimdall:
      image: linuxserver/heimdall
      container_name: heimdall
      environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TZ}
      volumes:
        - ${CONFIGDIR}/heimdall:/config
      ports:
        - 20080:80
        - 20443:443
      restart: unless-stopped