version: "3.7"

services:
  filebrowser:
    image: hurlenko/filebrowser
    user: "${UID}:${GID}"
    ports:
      - ${FILEBROWSER_PORT}:8080
    volumes:
      - ${CONFIGDIR}/filebrowser:/config
      - ${DATADIR}:/data
    environment:
      - FB_BASEURL=/
    restart: always