---
version: "2.1"
services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    environment:
      - PUID=${PUID} # User ID to run as
      - PGID=${PGID} # Group ID to run as
      - TZ=${TZ}
      # - PASSWORD= #optional
      # - CLI_ARGS= #optional
    volumes:
      - ${CONFIGDIR}/calibre:/config
    ports:
      - 8080:8080
      - 8081:8081
    restart: unless-stopped