---
version: "2.1"
services:
  nginx:
    image: lscr.io/linuxserver/nginx:latest
    container_name: nginx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${CONFIGDIR}/nginx:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped