---
version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:1.25.1
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - TZ=${TZ}
      # - PLEX_CLAIM=${PLEXTCLAIM}
    volumes:
      - ${CONFIGDIR}/plex:/config
      - ${PLEXDATA}/tv:/tv
      - ${PLEXDATA}/movies:/movies
    restart: unless-stopped