version: "3.5"

services:
  diun:
    image: crazymax/diun:latest
    network_mode: "bridge"
    container_name: diun
    volumes:
      - ${CONFIGDIR}/duin:/data
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - ${TZ}
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
      - "DIUN_WATCH_WORKERS=20"
      - "DIUN_WATCH_SCHEDULE=0 0 * * *"
      - "DIUN_PROVIDERS_DOCKER=true"
      - "DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true"
      - "DIUN_NOTIF_PUSHOVER_TOKEN=yourPushoverAppToken"
      - "DIUN_NOTIF_PUSHOVER_RECIPIENT=yourPushoverUserKey"
    restart: always